version: '3'
services:
    aethnode:
        image: "aeth/aeth:v0.16"
        ports:
            # open default aeth rpc port
            - "26657:26657"
            # open rest port
            - "1317:1317"
            # open grpc port
            - "9090:9090"
            # open grpc-web port
            - "9091:9091"
        volumes:
            - "./aeth/initstate/.aeth/config:/root/.aeth/config"
            - "./aeth/initstate/.aeth/keyring-test/:/root/.aeth/keyring-test"
        # start the blockchain, and set rpc to listen to connections from outside the container
        command: ["sh", "-c", "/root/.aeth/config/init-data-directory.sh && aeth start --rpc.laddr=tcp://0.0.0.0:26657"]
