version: '3'
services:
  aeth-1:
    image: "aeth/aeth:${AETH_IMAGE_TAG:-master}"
    ports:
      # open default aeth rpc port
      - "26657:26657"
      # open rest port
      - "1317:1317"
      # open grpc port
      - "9090:9090"
      # open grpc-web port
      - "9091:9091"
      # open EVM JSON-RPC port
      - "8545:8545"
      # open Eth websocket port
      - "8546:8546"
    volumes:
      - "./aeth-1:/root/.aeth"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.aeth/config/init-data-directory.sh && aeth start --rpc.laddr=tcp://0.0.0.0:26657"
  aeth-2:
    image: "aeth/aeth:${AETH_IMAGE_TAG:-master}"
    volumes:
      - "./aeth-2:/root/.aeth"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.aeth/config/init-data-directory.sh && aeth start --rpc.laddr=tcp://0.0.0.0:26657"
  aeth-3:
    image: "aeth/aeth:${AETH_IMAGE_TAG:-master}"
    volumes:
      - "./aeth-3:/root/.aeth"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.aeth/config/init-data-directory.sh && aeth start --rpc.laddr=tcp://0.0.0.0:26657"
  aeth-4:
    image: "aeth/aeth:${AETH_IMAGE_TAG:-master}"
    volumes:
      - "./aeth-4:/root/.aeth"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.aeth/config/init-data-directory.sh && aeth start --rpc.laddr=tcp://0.0.0.0:26657"
  aeth-5:
    image: "aeth/aeth:${AETH_IMAGE_TAG:-master}"
    volumes:
      - "./aeth-5:/root/.aeth"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.aeth/config/init-data-directory.sh && aeth start --rpc.laddr=tcp://0.0.0.0:26657"
  aeth-6:
    image: "aeth/aeth:${AETH_IMAGE_TAG:-master}"
    volumes:
      - "./aeth-6:/root/.aeth"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.aeth/config/init-data-directory.sh && aeth start --rpc.laddr=tcp://0.0.0.0:26657"
  aeth-7:
    image: "aeth/aeth:${AETH_IMAGE_TAG:-master}"
    volumes:
      - "./aeth-7:/root/.aeth"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.aeth/config/init-data-directory.sh && aeth start --rpc.laddr=tcp://0.0.0.0:26657"
  aeth-8:
    image: "aeth/aeth:${AETH_IMAGE_TAG:-master}"
    volumes:
      - "./aeth-8:/root/.aeth"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.aeth/config/init-data-directory.sh && aeth start --rpc.laddr=tcp://0.0.0.0:26657"
  aeth-9:
    image: "aeth/aeth:${AETH_IMAGE_TAG:-master}"
    volumes:
      - "./aeth-9:/root/.aeth"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.aeth/config/init-data-directory.sh && aeth start --rpc.laddr=tcp://0.0.0.0:26657"
  aeth-10:
    image: "aeth/aeth:${AETH_IMAGE_TAG:-master}"
    volumes:
      - "./aeth-10:/root/.aeth"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      - "sh"
      - "-c"
      - "/root/.aeth/config/init-data-directory.sh && aeth start --rpc.laddr=tcp://0.0.0.0:26657"
