version: '3'

services:
    ibcnode:
        image: "aeth/aeth:v0.16.1"
        ports:
            # open rpc port
            - "26658:26658"
            # open rest port
            - "1318:1318"
            # open grpc port
            - "9092:9092"
            # open grpc-web port
            - "9093:9093"
        volumes:
            - "./ibcchain/initstate/.aeth/config:/root/.aeth/config"
            - "./ibcchain/initstate/.aeth/keyring-test/:/root/.aeth/keyring-test"
        # start the blockchain, and set rpc to listen to connections from outside the container
        command: ["sh", "-c", "/root/.aeth/config/init-data-directory.sh && aeth start --rpc.laddr=tcp://0.0.0.0:26658"]
