version: "3"

services:
  aethnode:
    image: "aeth/aeth:v0.14.1"
    ports:
      # open default aeth rpc port
      - "26657:26657"
    volumes:
      - "./aeth/initstate/.kvd/config:/root/.kvd/config"
      - "./aeth/initstate/.kvcli/:/root/.kvcli/"
    # start the blockchain, and set rpc to listen to connections from outside the container
    command:
      [
        "sh",
        "-c",
        "/root/.kvd/config/init-data-directory.sh && kvd start --pruning=nothing --rpc.laddr=tcp://0.0.0.0:26657",
      ]
  aethrest:
    image: "aeth/aeth:v0.14.1"
    ports:
      # open default rest port
      - "1317:1317"
    command:
      [
        "kvcli",
        "rest-server",
        "--node=tcp://aethnode:26657",
        "--trust-node",
        "--laddr=tcp://0.0.0.0:1317",
        "--unsafe-cors",
      ]
